# Generated by Django 4.2.7 on 2024-03-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='course_img/')),
                ('price', models.IntegerField()),
                ('time', models.CharField(max_length=200)),
                ('enrolled_number', models.IntegerField()),
            ],
        ),
    ]
