# Generated by Django 4.2.7 on 2024-03-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecommunitymodel',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
