# Generated by Django 4.2.7 on 2024-04-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_from',
            new_name='valid_form',
        ),
    ]
